version: '3'
services:
  app:
    image: openjdk:11
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew bootRun
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .mongo-data:/data/db
